### ISSUE TITLE
Symbols

### ISSUE THREAD

**Issue by mikkomikkomikko** [Creatide/Sketch_Update-Text-Layer-Name#1]
Currently this is not working with the symbols :/ So do you have any plans to fix this?

**Comment by Creatide** [comment]
Sorry mate, but this addon is not meant to change the group/symbol names. This addon change only text items layer names, just that. It's because when you use custom names with groups/symbols you don't want their names to be changed without reason. It also quite problematic if you have many text items inside of group/symbol... There could be build totally new addon with options to affect groups and symbols, but not in this simple script.
